language: python
sudo: false
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYPI_USER_NAME: chaostoolkit
    - secure: "PY8lzPWHpLrBZ5CIXqRaNf6SnSWXp/PcZbDHjdNMHfKV3sFeUQCDRo9ynwp/kIqeG+AeENabNVd7NJrMAnh49EVTzi5dKC2ep21WgTjKHbmltDXwVARP26mHH5FexVqSDF36NuqdSnEFczo1fR0Ioqfi//9C9dzZLeojXfIo2pHj+3MtyL5XP4T+Lkc7vLfAObhl0UerYXmHTLsqu8/ysBkVEdtMfIGwSzarqsUFW93r5O3yr1ZLcC5txjK+vpTfsFwcZLoRlgIifl+FKCVl3yO6zC6I/aw/ISIXFV6NNNfZT003UiJKC52zyKmRDfVizqZg5VB80fjgTKLu6XgBHmvkjQqGP0eHiKJ/itVfwN5MEQYu2r00d7DG+de7YouIfoSYG7QSyg+U4AzQyx1CtooE7vU90qH+m+20JcbOBEAUp2EMiTa9gZ1KKYg/b59CQmyg4wCTsUijwo5H1d1kaWIL1S0uRfpuAMAtBKlaTiSTdU9ynaALgFQYhHZ3PLvJjutZO3nGCKEl9JneTvKpzen3rd6qhCrGXbkMBYkWSFCf/x7soQgX3F5EMjRY735umGuFdi084jgI6WyTKCeb+WRfY6KGg1WOeFXk+F9Nq3RsYAiBTgTWO6JZxM82TA+Tv/9bjbhbtiM7kb0SH87V0O7JdQaG+ppQb9kFTBftuFY="
python:
  - "3.6"
  - "3.7-dev"
install:
  - virtualenv --version
  - easy_install --version
  - pip --version
  - pip install --pre -r requirements.txt -r requirements-dev.txt
script:
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - "https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF"
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
