language: python
sudo: false
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYPI_USER_NAME: chaostoolkit
    - secure: "yl4cvZQbzujQJ0Q8okO58FaqXlGdGMgG2uDAPz1Lrrcgg+rdFE5eUag/r00+dgKf8g539RTJXbpgrA/0SXDRu4PXp+irliMei04IQZxEBlcNNIhY5OGiHHEg1U7CyEVxmxUKd3qDrY+TP0MXpFq+CAd5kVE9LniXvKQv7heNv+AKSB3LjGtvTaI3rEAlPxR7M99cFvAfuzR95nY14xF532zw5JH2eqdPgtvsLYpSUSKA99Uz3vfC9ZydonQDJNTa44WZmtYpBxwZxw4Psyj7DRkZf+DPEPnxW6knZOxYW9wkpUyBvtnaPnDo+mYjT5biBBBqRA6SYyhBY81gau+nKffLs7UQZmgInCMy8M+dfFLivfH7TDNJH83fecyOwUt0WO66SqUrv6F9k1rSC6sZCvQjMGEGQMwXDPHivVrHumxjgoBHURnY32nwimTCa5Z5+ohDWdQUSxXCcc/niVdG6efkfoNd2BwjNTCmOUPRAgnTQ2mzOZ/GINcIMO0A5xlBUVH7XbTJK0uaAkvWnxU9QkYZ0eD5QRGhsdcflpoULpOqW1DFCjb+zz78dAr2YOoEy8lflmdK2bOHp9PjwW1Dc7vbcYO8w07G+TSgi0uyIWigbnAY479TbhiiTORIeo7TzUJsaSJ8WZM6uzpey4qonGwnRpyRyXRCMRy1DHSa84U="
python:
  - "3.6"
  - "3.7-dev"
install:
  - virtualenv --version
  - easy_install --version
  - pip --version
  - pip install --pre -r requirements.txt -r requirements-dev.txt
script:
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - "https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF"
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
