language: python
sudo: false
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYPI_USER_NAME: chaostoolkit
    - secure: "JNZhLXAOh/YoEchRc9NYux5JEmy09rhw17dNFxds3AR6Xdab+W+IX8cZne3K9jLNqGq1pVuWx4dYqViPvLkfB685vEPR/ZS1NURfXt8274Ty7ls/bQyskr2gnFWto5xihlNIj8UGB18eyBU6pFyEJytwiYGvX3m7RlPP3YZCNMoCaS47lYoTo+xAYC82utRZrZOOggxV8rnQNFH1kwo5dAGPbiwZyVIBEKZwVYVYKc8L3yLQQnO3suI2ZtanrPKudHVawov5xg9Fe+32QaEFg/72AA5zj2Fzvt+jVmXm2DbF35ZKejqvEdv8tt4URYpnghHQo4QaWgMdvJ/Y4blms+3umnFVcD55kZLTqnpMEcvlG3HQBao1SofHdWOJpIn+CRAhhCjv6GX3DCMswClYVDbPDugQMZ18Qd2cHAT/WZKYkyJyc5lIVcPmStl32cEdZmBsYDpy9r+y7ZW0q4QwM693moPpISTERoB991tFfD6AfCMQn97LCWMS2AUU95p+NAasQE39GGfspd5xM4V4mGAWXCM+e1AlbFHr6x6YVnqTE6UjvY86DzaoUo8v8L6o9rjOVo6KplFevoX23D37Sqa8hw6DsPKa/VTQN/TUGMdhOcwUavQGr0hdL+APcnQnDs682l2fFGmxUiIJZYFIPMr/9DLTB4E5/Dd30UCJaCU="
python:
  - "3.6"
  - "3.7-dev"
install:
  - virtualenv --version
  - easy_install --version
  - pip --version
  - pip install --pre -r requirements.txt -r requirements-dev.txt
script:
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - "https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF"
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
